/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://sbah4d667jcnzjjgmbjz2yk6wi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-46jdrxebvnd4rhk7zfzx7rxzcu",
    "aws_cognito_identity_pool_id": "us-west-2:2cd41c2b-b5f0-4015-ae93-4f6d1fdb336b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_GJc4TpxrU",
    "aws_user_pools_web_client_id": "7ntlvmc8qu712vcnd4m4dm71b4",
    "oauth": {}
};


export default awsmobile;
